import { useEffect, useState } from 'react';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
type Turn={role:string;content:string}; type Session={id:string;stage:string;title:string};
export default function App(){
 const [access,setAccess]=useState(localStorage.getItem('access')||''); const [refresh,setRefresh]=useState(localStorage.getItem('refresh')||'');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [mode,setMode]=useState('login'); const [resetMode,setResetMode]=useState(false); const [resetToken,setResetToken]=useState(''); const [newPassword,setNewPassword]=useState(''); const [sessions,setSessions]=useState<Session[]>([]); const [sid,setSid]=useState(''); const [turns,setTurns]=useState<Turn[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [stage,setStage]=useState('intake');
 async function api(path:string, options:RequestInit={}){let res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(access?{Authorization:`Bearer ${access}`}:{}) ,...options.headers}}); if(res.status===401&&refresh&&path!='/auth/refresh'){const rr=await fetch(API+'/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh})});if(rr.ok){const t=await rr.json();setAccess(t.access_token);setRefresh(t.refresh_token);localStorage.setItem('access',t.access_token);localStorage.setItem('refresh',t.refresh_token);res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${t.access_token}`,...options.headers}})}} return res;}
 async function loadSessions(){const r=await api('/sessions');if(r.ok)setSessions(await r.json());}
 useEffect(()=>{if(access)loadSessions()},[access]);
 async function auth(e:React.FormEvent){e.preventDefault();setNotice('');const path=mode==='signup'?'/auth/signup':'/auth/login';const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setNotice(d.detail||'Could not authenticate');return}setAccess(d.access_token);setRefresh(d.refresh_token);localStorage.setItem('access',d.access_token);localStorage.setItem('refresh',d.refresh_token);}
 async function logout(){if(refresh)await api('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:refresh})});localStorage.clear();setAccess('');setRefresh('');setSid('');setTurns([])}
 async function forgot(){const r=await fetch(API+'/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});setNotice(r.ok?'If that account exists, a reset token was logged by the backend. Copy it from the API console, then enter it below.':'Enter a valid email first.');if(r.ok)setResetMode(true)}
 async function reset(e:React.FormEvent){e.preventDefault();const r=await fetch(API+'/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:resetToken,new_password:newPassword})});const d=await r.json();setNotice(r.ok?'Password updated. You can now log in.':(d.detail||'Could not reset password.'));if(r.ok){setResetMode(false);setMode('login');setPassword('');setResetToken('');setNewPassword('')}}
 async function newSession(){const r=await api('/sessions',{method:'POST',body:JSON.stringify({})});if(r.ok){const s=await r.json();setSid(s.id);setTurns([]);setStage(s.stage);loadSessions()}}
 async function openSession(id:string){const r=await api(`/sessions/${id}`);if(r.ok){const s=await r.json();setSid(id);setTurns(s.turns);setStage(s.stage)}}
 async function send(e:React.FormEvent){e.preventDefault();if(!message.trim())return;setBusy(true);let id=sid;if(!id){const r=await api('/sessions',{method:'POST',body:JSON.stringify({})});const s=await r.json();id=s.id;setSid(id)}const userMsg=message.trim();setMessage('');setTurns(t=>[...t,{role:'user',content:userMsg}]);const r=await api(`/sessions/${id}/chat`,{method:'POST',body:JSON.stringify({message:userMsg})});const d=await r.json();if(r.ok){setTurns(t=>[...t,{role:'assistant',content:d.reply}]);setStage(d.stage);setNotice(d.retrieved?.length?`Retrieved knowledge: ${d.retrieved.map((x:any)=>x.title).join(' · ')}`:'')}else setNotice(d.detail||'The assistant is temporarily unavailable.');setBusy(false);loadSessions()}
 function handleComposerKeyDown(e:React.KeyboardEvent<HTMLTextAreaElement>){if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(!busy&&message.trim())e.currentTarget.form?.requestSubmit()}}
 if(!access)return <main className="auth"><section className="card"><p className="eyebrow">CAREER NAVIGATOR</p><h1>{resetMode?'Reset your password':'Find a direction that fits.'}</h1><p>{resetMode?'Use the one-time token printed in the API console.':'Build your career profile in a conversation that remembers what matters to you.'}</p>{resetMode?<form onSubmit={reset}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Reset token<input required value={resetToken} onChange={e=>setResetToken(e.target.value)}/></label><label>New password<input type="password" minLength={10} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><button>Update password</button></form>:<form onSubmit={auth}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button>{mode==='signup'?'Create account':'Log in'}</button></form>}<div className="row"><button className="link" onClick={()=>{setResetMode(false);setMode(mode==='signup'?'login':'signup')}}>{mode==='signup'?'I have an account':'Create account'}</button>{!resetMode&&<button className="link" onClick={forgot}>Forgot password?</button>}</div>{notice&&<p className="notice">{notice}</p>}</section></main>;
 return <main className="shell"><aside><p className="eyebrow">CAREER NAVIGATOR</p><h2>Your journey</h2><button onClick={newSession}>＋ New conversation</button><div className="sessions">{sessions.map(s=><button className={sid===s.id?'selected':''} key={s.id} onClick={()=>openSession(s.id)}>{s.title||'Career exploration'}<small>{s.stage}</small></button>)}</div><button className="link" onClick={logout}>Log out</button></aside><section className="chat"><header><div><p className="eyebrow">DISCOVER · EXPLORE · DECIDE</p><h1>Career Navigator</h1></div><span className="stage">{stage}</span></header><div className="messages">{turns.length===0&&<div className="welcome"><h2>Let’s start with you.</h2><p>What kind of work or problems do you find interesting? No pressure at all!! I’ll ask follow-ups as we learn more.</p></div>}{turns.map((t,i)=><article key={i} className={`bubble ${t.role}`}>{t.content.split('\n').map((line,j)=><p key={j}>{line}</p>)}</article>)}{busy&&<article className="bubble assistant">Thinking through your profile…</article>}</div>{notice&&<div className="notice inline">{notice}</div>}<form className="composer" onSubmit={send}><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={handleComposerKeyDown} placeholder="Tell me what you enjoy, value, or want to change…" rows={2}/><button disabled={busy||!message.trim()}>Send</button></form></section></main>
}
